# Copyright (c) 2015, CodiLime Inc.

ds_haproxy_docker_image: "ds_haproxy"
docker_dir_prefix: "/tmp/docker-ansible"
ds_haproxy_download_dir: "{{docker_dir_prefix}}/{{ds_haproxy_docker_image}}"
docker_ip: "{{ansible_docker0.ipv4.address}}"
ds_documentation_ip: "{{docker_ip}}"
ds_documentation_port: 8001
ds_editor_ip: "{{docker_ip}}"
ds_editor_port: 8002
ds_wm_ip: "{{docker_ip}}"
ds_wm_port: 9081
ds_wm_public_port: 9080
static_allowed_http_req_rate_per_second_per_ip: 100
static_ip_block_period_in_seconds: 60
wm_allowed_http_req_rate_per_second_per_ip: 50
wm_ip_block_period_in_seconds: 60
syslog_server_ip: "{{docker_ip}}"
production_env: true
