# tasks file for supervisor

---
- name: Create supervisor configuration for {{program.name}}
  template:
    src: program.conf.j2
    dest: "/etc/supervisor/conf.d/{{program.name}}.conf"
    owner: root
    group: root
    mode: 0640
  notify: restart supervisor
