# Copyright (c) 2015, CodiLime Inc.

---
- name: Assures docker dir exists
  file: path={{docker_dir}}/nodejs state=directory

- name: Create dockerfile for nodejs
  template: src=Dockerfile.j2 dest="{{docker_dir}}/nodejs/Dockerfile"

- name: Build nodejs docker image
  docker_image: path="{{docker_dir}}/nodejs" name="ds-nodejs-{{node_package_version}}" state=build
