# Copyright (c) 2016, CodiLime Inc.

---
dependencies:
- { role: supervisedprogram,
    program: {
      name: 'WorkflowExecutor',
      environment: 'SPARK_HOME="{{spark_install_dir}}/spark", PYTHONPATH="{{spark_install_dir}}/spark/python:{{spark_install_dir}}/spark/python/build:$PYTHONPATH"',
      command: '{{spark_install_dir}}/spark/bin/spark-submit --class io.deepsense.workflowexecutor.WorkflowExecutorApp --master local[8] --driver-class-path "{{extra_jars}}/{{mysql_connector_jar_id}}.jar:{{extra_jars}}/{{postgresql_connector_jar_id}}.jar:{{workflowexecutor_artifact_id}}.jar" {{workflowexecutor_artifact_id}}.jar --interactive-mode -m localhost -p {{workflowexecutor_artifact_id}}.jar',
      directory: "{{install_dir}}",
      autostart: true,
      autorestart: true,
      startretries: 3,
      stdout_logfile: "{{install_dir}}/std.out",
      stdout_logfile_maxbytes: 0,
      stderr_logfile: "{{install_dir}}/std.err",
      stderr_logfile_maxbytes: 0,
      user: ubuntu,
    }
  }
