# Copyright (c) 2015, CodiLime Inc.

---
- include: ../../../tasks/deploy_package.yml
  vars:
    artifactid: "{{ge_artifact_id}}"
    version: "{{ge_version}}"
    package_path: "{{download_dir}}/{{artifactid}}.zip"

- name: Prepare hdfs deployment script
  template: src=hdfs_deployment.sh dest="{{ge_install_dir}}/hdfs_deployment.sh"

- name: Prepare configuration file
  template: src=application.conf.j2 dest="{{ge_install_dir}}/application.conf"

- name: Send log4j.xml
  copy: src=log4j.xml dest="{{ge_install_dir}}/log4j.xml"

- name: Deploy graphexecutor on hdfs
  command: "docker exec -it -u hadoop ds-hadoop bash {{ge_install_dir}}/hdfs_deployment.sh"
