# Copyright (c) 2016, CodiLime Inc.

---
dependencies:
- { role: supervisedprogram,
    program: {
      name: 'WorkflowManager',
      command: '{{install_dir}}/deepsense-workflowmanager/bin/deepsense-workflowmanager -Dconfig.file={{install_dir}}/application.conf -DlogFile=/home/ubuntu/log/deepsense/wm/deepsense-workflowmanager',
      directory: "{{install_dir}}",
      autostart: true,
      autorestart: true,
      startretries: 3,
      stdout_logfile: "{{install_dir}}/std.out",
      stdout_logfile_maxbytes: 0,
      stderr_logfile: "{{install_dir}}/std.err",
      stderr_logfile_maxbytes: 0,
      user: ubuntu,
    }
  }
