# Copyright (c) 2016, CodiLime Inc.

---
dependencies:
- { role: supervisedprogram,
    program: {
      name: 'Jupyter',
      environment: 'HOME="/home/ubuntu", USER="ubuntu"',
      command: '{{jupyter_workdir}}/start-notebook.sh',
      directory: "{{jupyter_workdir}}",
      autostart: true,
      autorestart: true,
      startretries: 3,
      stdout_logfile: "{{jupyter_workdir}}/std.out",
      stdout_logfile_maxbytes: 0,
      stderr_logfile: "{{jupyter_workdir}}/std.err",
      stderr_logfile_maxbytes: 0,
      user: ubuntu,
    }
  }
