# Copyright (c) 2015, CodiLime Inc.

---
- name: Delete existing SQL files
  file: path="{{sql_dir}}/{{module}}" state=absent

- name: Copy SQL files
  copy: src="{{module}}" dest="{{sql_dir}}/{{module}}" force=true

- name: Copy h2 jar
  copy: src="{{download_dir}}/{{h2_filename}}" dest="{{sql_dir}}/{{module}}"

- name: Find all SQL files
  shell: "find {{sql_dir}}/{{module}} -name '*.sql' | sort"
  register: sql_files

- name: Execute all SQL files
  command: "java -cp h2-1.4.191.jar org.h2.tools.RunScript -url jdbc:h2:{{ database }} -script {{ item }}"
  with_items: "{{sql_files.stdout_lines}}"
  args:
    chdir: "{{sql_dir}}/{{module}}"

- name: Set DB file permissions
  file: path="{{ database }}.mv.db" mode=0666
