# Copyright (c) 2015, CodiLime Inc.

---
- name: Create conda directory
  file: path={{conda_dir}} state=directory owner=ubuntu

- name: Create jupyter directory
  file: path=/home/ubuntu/.jupyter state=directory owner=ubuntu

- name: Install miniconda
  shell: sudo -u ubuntu /tmp/{{miniconda_filename}} -f -b -p {{conda_dir}}

- name: Install conda
  shell: sudo -u ubuntu {{conda_dir}}/bin/conda install --yes conda

- name: Install notebook
  shell: sudo -u ubuntu {{conda_dir}}/bin/conda install --yes notebook terminado

- name: Install python packages
  shell: sudo -u ubuntu {{conda_dir}}/bin/conda install --yes -c https://conda.anaconda.org/prometeia \
    'ipython=4.0*' \
    'ipywidgets=4.0*' \
    'pandas=0.16*' \
    'matplotlib=1.4*' \
    'scipy=0.15*' \
    'seaborn=0.6*' \
    'scikit-learn=0.16*' \
    'pika=0.10*' \
    pyzmq

- name: Install ipython kernel
  shell: "{{conda_dir}}/bin/python {{conda_dir}}/bin/ipython kernelspec install-self"

- name: Install py4j
  shell: "{{conda_dir}}/bin/pip install py4j"

- name: Copy pyspark kernel files
  copy: src=kernels dest=/tmp/

- name: Create config file for pyspark kernel
  template: src=kernel.json.j2 dest=/tmp/kernels/pyspark/kernel.json

- name: Install pyspark kernel
  shell: "{{conda_dir}}/bin/jupyter-kernelspec install /tmp/kernels/pyspark"

- name: Copy wmcontents
  copy: src=wmcontents dest={{conda_dir}}/lib/python2.7/site-packages/

- name: Set up pyspark to use conda env
  lineinfile: dest={{spark_install_dir}}/spark/conf/spark-env.sh line="source {{conda_dir}}/bin/activate {{conda_dir}}"

- name: Set up PYSPARK_PYTHON env variable
  lineinfile: dest={{spark_install_dir}}/spark/conf/spark-env.sh line="export PYSPARK_PYTHON={{conda_dir}}/bin/python"

- name: Set up PYSPARK_DRIVER_PYTHON env variable
  lineinfile: dest={{spark_install_dir}}/spark/conf/spark-env.sh line="export PYSPARK_DRIVER_PYTHON={{conda_dir}}/bin/python"

- name: Create jupyter workdir
  file: path={{jupyter_workdir}} state=directory owner=ubuntu

- name: Create config file for jupyter
  template: src=jupyter_notebook_config.py.j2 dest={{jupyter_workdir}}/jupyter_notebook_config.py

- name: Create startup script
  template: src=start-notebook.sh.j2 dest={{jupyter_workdir}}/start-notebook.sh mode=755

- name: Force supervisor restart
  command: /bin/true
  notify: restart supervisor
