# Copyright (c) 2015, CodiLime Inc.

---
- name: Remove directory
  file: path="{{livy_install_dir}}/{{livy_directory_name}}" state=absent

- name: Create directory
  file: path="{{livy_install_dir}}" state=directory mode=0755

- name: Copy livy package
  copy: src="{{download_dir}}/{{livy_filename}}" dest="/tmp/{{livy_filename}}" force=true

- name: Unpack livy package
  unarchive: src="/tmp/{{livy_filename}}" dest="{{livy_install_dir}}" creates="{{livy_directory_name}}" copy=no

- name: Create livy link
  file: src="{{livy_directory_name}}" dest="{{livy_install_dir}}/{{livy_artifactid}}" state=link

- name: Force supervisor restart
  command: /bin/true
  notify: restart supervisor
