# Copyright (c) 2015, CodiLime Inc.

- name: "Remove download directory"
  command: "/bin/rm -rf {{download_dir}}"

- name: "Create download directory"
  file:
    path: "{{download_dir}}"
    state: directory
    mode: 0755
