# Copyright (c) 2015, CodiLime Inc.

- name: "Install unzip"
  apt: package=unzip state=latest

- name: "Remove directory"
  command: "/bin/rm -rf {{install_dir}}/*"

- name: "Create directory"
  file:
    path: "{{install_dir}}"
    state: directory
    mode: 0755

- name: Copy zip package
  copy:
    src="{{package_path}}"
    dest="{{install_dir}}"
    force=true

- name: Extract zip package
  unarchive:
    src: "{{install_dir}}/{{artifactid}}.zip"
    dest: "{{install_dir}}"
    copy: no

- name: Symlink home directory
  file:
    src: "{{artifactid}}-{{version}}"
    path: "{{install_dir}}/{{artifactid}}"
    state: link
