# Copyright (c) 2016, CodiLime Inc.

# TODO check if artifactory_get task could be used

- name: Download h2 package
  artifactory:
    base_url: "{{artifactory_base_url}}"
    repository: "ext-third-party"
    groupid: "{{h2_groupid}}"
    artifactid: "{{h2_artifactid}}"
    version: "{{h2_version}}"
    path: "{{download_dir}}/"
    filename: "{{h2_filename}}"
