version: '2'
services:
  workflowmanager:
    ports:
     - "9080:9080"
    image: docker-repo.deepsense.codilime.com/tap/deepsense-workflowmanager:seahorse_on_tap-latest
    environment:
      - WM_AUTH_USER=Some_User
      - WM_AUTH_PASS=Some_Password
  sessionmanager:
    ports:
      - "9082:9082"
    image: docker-repo.deepsense.codilime.com/tap/deepsense-sessionmanager:seahorse_on_tap-latest
    volumes:
      - ./yarn-remote-client:/yarn-remote-client:ro
    environment:
      - MQ_HOST=rabbitmq
      - MQ_PORT=5672
      - WM_HOST=workflowmanager
      - WM_PORT=9080
      - WM_AUTH_USER=Some_User
      - WM_AUTH_PASS=Some_Password
      - SESSION_EXECUTOR_PATH=/opt/docker/we.jar
      - SESSION_EXECUTOR_DEPS_PATH=/opt/docker/we-deps.zip
      - HADOOP_CONF_DIR=/yarn-remote-client
      - SM_MQ_HOST=rabbitmq
      - SM_MQ_PORT=5672
    links:
      - rabbitmq
      - workflowmanager
      - sandbox
  frontend:
    image: docker-repo.deepsense.codilime.com/tap/deepsense-frontend:seahorse_on_tap-latest
    environment:
      - API_HOST=http://localhost
      - API_PORT=8080
      - SESSION_API_PORT=8080
      - MQ_USER=guest
      - MQ_PASS=guest
      - SOCKETS_ADDRESS=http://localhost:8080/
      - NOTEBOOKS_HOST=http://localhost:8080/jupyter
    ports:
      - "80:80"
    depends_on:
      - rabbitmq
      - workflowmanager
      - sessionmanager
      - notebooks
  rabbitmq:
    image: docker-repo.deepsense.codilime.com/tap/deepsense-rabbitmq:seahorse_on_tap-latest
    ports:
     - "15674:15674"
     - "15672:15672"
     - "5672:5672"
    environment:
     - RABBITMQ_USER=guest
     - RABBITMQ_PASS=guest
  notebooks:
    image: docker-repo.deepsense.codilime.com/tap/deepsense-notebooks:seahorse_on_tap-latest
    links:
      - workflowmanager
      - rabbitmq
    ports:
      - "9999:8888"
    environment:
      - WM_URL=http://workflowmanager:9080
      - WM_AUTH_USER=Some_User
      - WM_AUTH_PASS=Some_Password
      - MQ_HOST=rabbitmq
      - MQ_PORT=5672
      - HEARTBEAT_INTERVAL=2.0
      - MISSED_HEARTBEAT_LIMIT=60
  sandbox: # Yarn and yarn clients rely on name 'sandbox'
    image: docker-repo.deepsense.codilime.com/tap/deepsense-spark-yarn:seahorse_on_tap-latest
    hostname: sandbox
    links:
      - workflowmanager
      - rabbitmq
    ports:
      - sandbox:8030:8030
      - sandbox:8032:8032
      - sandbox:8088:8088
      - sandbox:8031:8031
      - sandbox:8033:8033
      - sandbox:9000:9000
      - sandbox:8042:8042
  proxy:
    image: docker-repo.deepsense.codilime.com/tap/deepsense-proxy:seahorse_on_tap-latest
    ports:
      - "8080:8080"
    environment:
      VCAP_SERVICES: "{\"user-provided\":[{\"credentials\":{\"authorizationUri\":\"http://login.seahorse.gotapaas.eu/oauth/authorize\",\"logoutUri\":\"http://login.seahorse.gotapaas.eu/logout.do\",\"tokenUri\":\"http://uaa.seahorse.gotapaas.eu/oauth/token\",\"clientId\":\"seahorse_client_2\",\"clientSecret\":\"seahorse01\",\"userInfoUri\":\"http://login.seahorse.gotapaas.eu/userinfo\"},\"name\":\"sso\"},{\"credentials\":{\"host\":\"http://workflowmanager:9080\"},\"name\":\"workflow-manager\"},{\"credentials\":{\"host\":\"http://sessionmanager:9082\"},\"name\":\"session-manager\"},{\"credentials\":{\"host\":\"http://notebooks:8888\"},\"name\":\"jupyter\"},{\"credentials\":{\"host\":\"http://rabbitmq:15674\"},\"name\":\"rabbitmq\"},{\"credentials\":{\"host\":\"http://frontend:80\"},\"name\":\"frontend\"}]}"
      WM_AUTH_USER: "Some_User"
      WM_AUTH_PASS: "Some_Password"

