version: '2'
services:
  workflowmanager:
    ports:
     - "9080:9080"
    image: quay.io/deepsense_io/deepsense-workflowmanager:seahorse_on_bdu-latest
    environment:
      - WM_AUTH_USER=oJkTZ8BV
      - WM_AUTH_PASS=8Ep9GqRr
  sessionmanager:
    hostname: sessionmanager
    ports:
      - "9082:9082"
    image: quay.io/deepsense_io/deepsense-sessionmanager:seahorse_on_bdu-latest
    environment:
      - MQ_HOST=rabbitmq
      - MQ_PORT=5672
      - WM_HOST=workflowmanager
      - WM_PORT=9080
      - WM_AUTH_USER=oJkTZ8BV
      - WM_AUTH_PASS=8Ep9GqRr
      - SESSION_EXECUTOR_PATH=/opt/docker/we.jar
      - SESSION_EXECUTOR_DEPS_PATH=/opt/docker/we-deps.zip
      - HADOOP_CONF_DIR=/opt/docker/yarn-remote-client
      - SM_MQ_HOST=rabbitmq
      - SM_MQ_PORT=5672
      - TEMP_DIR=/tmp/seahorse/download
    links:
      - rabbitmq
      - workflowmanager
    depends_on:
      - rabbitmq
  frontend:
    image: quay.io/deepsense_io/deepsense-frontend:seahorse_on_bdu-latest
    environment:
      - API_HOST=http://localhost
      - API_PORT=8080
      - SESSION_API_PORT=8080
      - MQ_USER=guest
      - MQ_PASS=guest
      - SOCKETS_ADDRESS=http://localhost:8080/
      - NOTEBOOKS_HOST=http://localhost:8080/jupyter
    ports:
      - "80:80"
    depends_on:
      - rabbitmq
      - workflowmanager
      - sessionmanager
      - notebooks
  rabbitmq:
    image: quay.io/deepsense_io/deepsense-rabbitmq:seahorse_on_bdu-latest
    ports:
     - "15674:15674"
     - "15672:15672"
     - "5672:5672"
    environment:
     - RABBITMQ_USER=guest
     - RABBITMQ_PASS=guest
  notebooks:
    image: quay.io/deepsense_io/deepsense-notebooks:seahorse_on_bdu-latest
    links:
      - workflowmanager
      - rabbitmq
    ports:
      - "9999:8888"
    environment:
      - WM_URL=http://workflowmanager:9080
      - WM_AUTH_USER=oJkTZ8BV
      - WM_AUTH_PASS=8Ep9GqRr
      - MQ_HOST=rabbitmq
      - MQ_PORT=5672
      - HEARTBEAT_INTERVAL=2.0
      - MISSED_HEARTBEAT_LIMIT=60
  proxy:
    image: quay.io/deepsense_io/deepsense-proxy:seahorse_on_bdu-latest
    ports:
      - "8080:8080"
    environment:
      VCAP_SERVICES: "{\"user-provided\":[{\"credentials\":{\"host\":\"http://workflowmanager:9080\"},\"name\":\"workflow-manager\"},{\"credentials\":{\"host\":\"http://sessionmanager:9082\"},\"name\":\"session-manager\"},{\"credentials\":{\"host\":\"http://notebooks:8888\"},\"name\":\"jupyter\"},{\"credentials\":{\"host\":\"http://rabbitmq:15674\"},\"name\":\"rabbitmq\"},{\"credentials\":{\"host\":\"http://frontend:80\"},\"name\":\"frontend\"}]}"
      DISABLE_OAUTH: "true"
      WM_AUTH_USER: "oJkTZ8BV"
      WM_AUTH_PASS: "8Ep9GqRr"

