version: '2'
services:
  proxy:
    image: quay.io/deepsense_io/deepsense-proxy:seahorse_on_bdu-latest
    ports:
      - "${SEAHORSE_PORT}:8080"
    environment:
      VCAP_SERVICES: "{\"user-provided\":[{\"credentials\":{\"host\":\"http://workflowmanager:9080\"},\"name\":\"workflow-manager\"},{\"credentials\":{\"host\":\"http://sessionmanager:9082\"},\"name\":\"session-manager\"},{\"credentials\":{\"host\":\"http://notebooks:8888\"},\"name\":\"jupyter\"},{\"credentials\":{\"host\":\"http://rabbitmq:15674\"},\"name\":\"rabbitmq\"},{\"credentials\":{\"host\":\"http://frontend:80\"},\"name\":\"frontend\"}]}"
      DISABLE_OAUTH: "true"
      FORCE_HTTPS: "false"
      WM_AUTH_USER: "oJkTZ8BV"
      WM_AUTH_PASS: "8Ep9GqRr"
    links:
      - workflowmanager
      - sessionmanager
      - notebooks
      - rabbitmq
      - frontend
    depends_on:
      - workflowmanager
      - sessionmanager
      - notebooks
      - rabbitmq
      - frontend
  frontend:
    image: quay.io/deepsense_io/deepsense-frontend:seahorse_on_bdu-latest
    environment:
      - "API_HOST=http://${SEAHORSE_HOST}"
      - "API_PORT=${SEAHORSE_PORT}"
      - "SESSION_API_PORT=${SEAHORSE_PORT}"
      - "MQ_USER=guest"
      - "MQ_PASS=guest"
      - "SOCKETS_ADDRESS=http://${SEAHORSE_HOST}:${SEAHORSE_PORT}/"
      - "NOTEBOOKS_HOST=http://${SEAHORSE_HOST}:${SEAHORSE_PORT}/jupyter"
    links:
      - rabbitmq
      - workflowmanager
      - sessionmanager
      - notebooks
    depends_on:
      - rabbitmq
      - workflowmanager
      - sessionmanager
      - notebooks
  sessionmanager:
    image: quay.io/deepsense_io/deepsense-sessionmanager:seahorse_on_bdu-latest
    hostname: sessionmanager
    environment:
      - "MQ_HOST=rabbitmq"
      - "MQ_PORT=5672"
      - "WM_HOST=workflowmanager"
      - "WM_PORT=9080"
      - "WM_AUTH_USER=oJkTZ8BV"
      - "WM_AUTH_PASS=8Ep9GqRr"
      - "SESSION_EXECUTOR_PATH=/opt/docker/we.jar"
      - "SESSION_EXECUTOR_DEPS_PATH=/opt/docker/we-deps.zip"
      - "HADOOP_CONF_DIR=/opt/docker/yarn-remote-client"
      - "SM_MQ_HOST=rabbitmq"
      - "SM_MQ_PORT=5672"
      - "TEMP_DIR=/tmp/seahorse/download"
    volumes:
      - "${DATA_DIR}:/resources/data"
    links:
      - rabbitmq
      - workflowmanager
    depends_on:
      - rabbitmq
      - workflowmanager
  notebooks:
    image: quay.io/deepsense_io/deepsense-notebooks:seahorse_on_bdu-latest
    environment:
      - "WM_URL=http://workflowmanager:9080"
      - "WM_AUTH_USER=oJkTZ8BV"
      - "WM_AUTH_PASS=8Ep9GqRr"
      - "MQ_HOST=rabbitmq"
      - "MQ_PORT=5672"
      - "HEARTBEAT_INTERVAL=2.0"
      - "MISSED_HEARTBEAT_LIMIT=30"
    links:
      - rabbitmq
      - workflowmanager
    depends_on:
      - rabbitmq
      - workflowmanager
  workflowmanager:
    image: quay.io/deepsense_io/deepsense-workflowmanager:seahorse_on_bdu-latest
    environment:
      - "WM_AUTH_USER=oJkTZ8BV"
      - "WM_AUTH_PASS=8Ep9GqRr"
  rabbitmq:
    image: quay.io/deepsense_io/deepsense-rabbitmq:seahorse_on_bdu-latest
    environment:
     - "RABBITMQ_USER=guest"
     - "RABBITMQ_PASS=guest"
