version: '2'
services:
  proxy:
    image: $DOCKER_REPOSITORY/deepsense-proxy:$BACKEND_TAG
    restart: always
    network_mode: "host"
    environment: &proxy_environment_value
      VCAP_SERVICES: "{\"user-provided\":[{\"credentials\":{\"host\":\"http://127.0.0.1:$EXPOSED_AUTHORIZATION_PORT\",\"authorizationUri\":\"/authorization/oauth/authorize\",\"logoutUri\":\"/authorization/logout.do\",\"tokenUri\":\"http://127.0.0.1:$EXPOSED_AUTHORIZATION_PORT/authorization/oauth/token\",\"clientId\":\"Seahorse\",\"clientSecret\":\"seahorse01\",\"userInfoUri\":\"http://127.0.0.1:$EXPOSED_AUTHORIZATION_PORT/authorization/userinfo\"},\"name\":\"sso\"},{\"credentials\":{\"host\":\"http://127.0.0.1:$EXPOSED_WM_PORT\"},\"name\":\"workflow-manager\"},{\"credentials\":{\"host\":\"http://127.0.0.1:$EXPOSED_LIBRARY_PORT\"},\"name\":\"library\"},{\"credentials\":{\"host\":\"http://127.0.0.1:$EXPOSED_SM_PORT\"},\"name\":\"session-manager\"},{\"credentials\":{\"host\":\"http://127.0.0.1:$EXPOSED_NOTEBOOK_PORT\"},\"name\":\"jupyter\"},{\"credentials\":{\"host\":\"http://127.0.0.1:$EXPOSED_MQ_WEBSOCKET_PORT\"},\"name\":\"rabbitmq\"},{\"credentials\":{\"host\":\"http://127.0.0.1:$EXPOSED_FRONTEND_PORT\"},\"name\":\"frontend\"}]}"
      HOST: "127.0.0.1"
      PORT: "33321"
      ENABLE_AUTHORIZATION: "false"
      FORCE_HTTPS: "false"
      WM_AUTH_USER: "oJkTZ8BV"
      WM_AUTH_PASS: "8Ep9GqRr"
    depends_on:
      - workflowmanager
      - sessionmanager
      - library
      - notebooks
      - rabbitmq
      - frontend
  frontend:
    image: $DOCKER_REPOSITORY/deepsense-frontend:$FRONTEND_TAG
    restart: always
    ports:
      - "127.0.0.1:$EXPOSED_FRONTEND_PORT:80"
    environment:
      - "PORT=80"
      - "SESSION_POLLING_INTERVAL=1000"
      - "MQ_USER=yNNp7VJS"
      - "MQ_PASS=1ElYfGNW"
      - "API_VERSION=$API_VERSION"
    links:
      - rabbitmq
      - workflowmanager
      - library
      - notebooks
    depends_on:
      - rabbitmq
      - workflowmanager
      - sessionmanager
      - library
      - notebooks
  sessionmanager:
    image: $DOCKER_REPOSITORY/deepsense-sessionmanager:$BACKEND_TAG
    restart: always
    network_mode: "host"
    environment:
      - "SM_HOST=127.0.0.1"
      - "SM_PORT=$EXPOSED_SM_PORT"
      - "SM_MQ_HOST=127.0.0.1"
      - "SM_MQ_PORT=$EXPOSED_MQ_PORT"
      - "MQ_PORT=$EXPOSED_MQ_PORT"
      - "MQ_USER=yNNp7VJS"
      - "MQ_PASS=1ElYfGNW"
      - "WM_PORT=$EXPOSED_WM_PORT"
      - "WM_AUTH_USER=oJkTZ8BV"
      - "WM_AUTH_PASS=8Ep9GqRr"
      - "PYTHON_DRIVER_BINARY=/opt/conda/bin/python"
      - "PYTHON_EXECUTOR_BINARY=python"
      - "SPARK_APPLICATIONS_LOGS_DIR=/spark_applications_logs"
      - "SESSION_EXECUTOR_PATH=/opt/docker/we.jar"
      - "SESSION_EXECUTOR_DEPS_PATH=/opt/docker/we-deps.zip"
      - "SPARK_RESOURCES_JARS=/resources/jars"
      - "TEMP_DIR=/tmp/seahorse/download"
      - "JDBC_URL=jdbc:h2:tcp://127.0.0.1:$EXPOSED_DB_PORT/sessionmanager;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1"
    volumes:
      - "./data:/resources/data"
      - "./jars:/resources/jars"
      - "library:/library"
      - "./R_Libs:/opt/R_Libs"
      - "./spark_applications_logs:/spark_applications_logs:rw"
    depends_on:
      - rabbitmq
      - workflowmanager
      - library
      - database
  notebooks:
    image: $DOCKER_REPOSITORY/deepsense-notebooks:$BACKEND_TAG
    restart: always
    ports:
      - "127.0.0.1:$EXPOSED_NOTEBOOK_PORT:8888"
    environment:
      - "WM_URL=http://workflowmanager:9080"
      - "WM_AUTH_USER=oJkTZ8BV"
      - "WM_AUTH_PASS=8Ep9GqRr"
      - "MQ_HOST=rabbitmq"
      - "MQ_PORT=5672"
      - "MQ_USER=yNNp7VJS"
      - "MQ_PASS=1ElYfGNW"
      - "HEARTBEAT_INTERVAL=2.0"
      - "MISSED_HEARTBEAT_LIMIT=30"
    links:
      - rabbitmq
      - workflowmanager
    depends_on:
      - rabbitmq
      - workflowmanager
  workflowmanager:
    image: $DOCKER_REPOSITORY/deepsense-workflowmanager:$BACKEND_TAG
    restart: always
    ports:
     - "127.0.0.1:$EXPOSED_WM_PORT:9080"
    environment:
      - "WM_AUTH_USER=oJkTZ8BV"
      - "WM_AUTH_PASS=8Ep9GqRr"
    volumes:
      - "./jars:/resources/jars"
    links:
      - database
  datasourcemanager:
    image: $DOCKER_REPOSITORY/deepsense-datasourcemanager:$BACKEND_TAG
    restart: always
    ports:
     - "127.0.0.1:$EXPOSED_DATASOURCES_MANAGER_PORT:8080"
    environment:
      - "JDBC_URL=jdbc:h2:tcp://database:1521/datasourcemanager;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1"
    links:
      - database
  rabbitmq:
    image: $DOCKER_REPOSITORY/deepsense-rabbitmq:$BACKEND_TAG
    restart: always
    ports:
     - "127.0.0.1:$EXPOSED_MQ_PORT:5672"
     - "127.0.0.1:$EXPOSED_MQ_WEBSOCKET_PORT:15674"
    environment:
     - "RABBITMQ_USER=yNNp7VJS"
     - "RABBITMQ_PASS=1ElYfGNW"
  database:
    image: $DOCKER_REPOSITORY/deepsense-h2:$BACKEND_TAG
    restart: always
    ports:
     - "127.0.0.1:$EXPOSED_DB_PORT:1521"
    volumes:
      - "./h2-data:/opt/h2-data:rw"
  library:
    image: $DOCKER_REPOSITORY/deepsense-libraryservice:$BACKEND_TAG
    restart: always
    ports:
     - "127.0.0.1:$EXPOSED_LIBRARY_PORT:9083"
    volumes:
      - "library:/library"
  authorization:
    image: $DOCKER_REPOSITORY/deepsense-authorization:$BACKEND_TAG
    restart: always
    ports:
     - "127.0.0.1:$EXPOSED_AUTHORIZATION_PORT:8080"
    environment: *proxy_environment_value
    volumes:
      - "./uaa:/uaa:rw"
    links:
      - database
volumes:
  library:
