version: '2'
services:
  proxy:
    image: $DOCKER_REPOSITORY/deepsense-proxy:$DOCKER_TAG
    network_mode: "host"
    environment:
      VCAP_SERVICES: "{\"user-provided\":[{\"credentials\":{\"host\":\"http://127.0.0.1:$EXPOSED_WM_PORT\"},\"name\":\"workflow-manager\"},{\"credentials\":{\"host\":\"http://127.0.0.1:$EXPOSED_LIBRARY_PORT\"},\"name\":\"library\"},{\"credentials\":{\"host\":\"http://127.0.0.1:$EXPOSED_SM_PORT\"},\"name\":\"session-manager\"},{\"credentials\":{\"host\":\"http://127.0.0.1:$EXPOSED_NOTEBOOK_PORT\"},\"name\":\"jupyter\"},{\"credentials\":{\"host\":\"http://127.0.0.1:$EXPOSED_MQ_WEBSOCKET_PORT\"},\"name\":\"rabbitmq\"},{\"credentials\":{\"host\":\"http://127.0.0.1:$EXPOSED_FRONTEND_PORT\"},\"name\":\"frontend\"}]}"
      HOST: "127.0.0.1"
      PORT: "33321"
      DISABLE_OAUTH: "true"
      FORCE_HTTPS: "false"
      WM_AUTH_USER: "oJkTZ8BV"
      WM_AUTH_PASS: "8Ep9GqRr"
    depends_on:
      - workflowmanager
      - sessionmanager
      - library
      - notebooks
      - rabbitmq
      - frontend
  frontend:
    image: $DOCKER_REPOSITORY/deepsense-frontend:$DOCKER_TAG
    ports:
      - "127.0.0.1:$EXPOSED_FRONTEND_PORT:80"
    environment:
      - "PORT=80"
      - "SESSION_POLLING_INTERVAL=1000"
      - "MQ_USER=yNNp7VJS"
      - "MQ_PASS=1ElYfGNW"
    links:
      - rabbitmq
      - workflowmanager
      - library
      - notebooks
    depends_on:
      - rabbitmq
      - workflowmanager
      - sessionmanager
      - library
      - notebooks
  sessionmanager:
    image: $DOCKER_REPOSITORY/deepsense-sessionmanager:$DOCKER_TAG
    network_mode: "host"
    environment:
      - "SM_HOST=127.0.0.1"
      - "SM_PORT=$EXPOSED_SM_PORT"
      - "SM_MQ_HOST=127.0.0.1"
      - "SM_MQ_PORT=$EXPOSED_MQ_PORT"
      - "MQ_PORT=$EXPOSED_MQ_PORT"
      - "MQ_USER=yNNp7VJS"
      - "MQ_PASS=1ElYfGNW"
      - "WM_PORT=$EXPOSED_WM_PORT"
      - "WM_AUTH_USER=oJkTZ8BV"
      - "WM_AUTH_PASS=8Ep9GqRr"
      - "PYTHON_DRIVER_BINARY=/opt/conda/bin/python"
      - "PYTHON_EXECUTOR_BINARY=python"
      - "SESSION_EXECUTOR_PATH=/opt/docker/we.jar"
      - "SESSION_EXECUTOR_DEPS_PATH=/opt/docker/we-deps.zip"
      - "TEMP_DIR=/tmp/seahorse/download"
      - "JDBC_URL=jdbc:h2:tcp://127.0.0.1:$EXPOSED_DB_PORT/sessionmanager;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1"
    volumes:
      - "./data:/resources/data"
      - "library:/library"
    depends_on:
      - rabbitmq
      - workflowmanager
      - library
      - database
  notebooks:
    image: $DOCKER_REPOSITORY/deepsense-notebooks:$DOCKER_TAG
    ports:
      - "127.0.0.1:$EXPOSED_NOTEBOOK_PORT:8888"
    environment:
      - "WM_URL=http://workflowmanager:9080"
      - "WM_AUTH_USER=oJkTZ8BV"
      - "WM_AUTH_PASS=8Ep9GqRr"
      - "MQ_HOST=rabbitmq"
      - "MQ_PORT=5672"
      - "MQ_USER=yNNp7VJS"
      - "MQ_PASS=1ElYfGNW"
      - "HEARTBEAT_INTERVAL=2.0"
      - "MISSED_HEARTBEAT_LIMIT=30"
    links:
      - rabbitmq
      - workflowmanager
    depends_on:
      - rabbitmq
      - workflowmanager
  workflowmanager:
    image: $DOCKER_REPOSITORY/deepsense-workflowmanager:$DOCKER_TAG
    ports:
     - "0.0.0.0:$EXPOSED_WM_PORT:9080"
    environment:
      - "WM_AUTH_USER=oJkTZ8BV"
      - "WM_AUTH_PASS=8Ep9GqRr"
    links:
      - database
  rabbitmq:
    image: $DOCKER_REPOSITORY/deepsense-rabbitmq:$DOCKER_TAG
    ports:
     - "0.0.0.0:$EXPOSED_MQ_PORT:5672"
     - "127.0.0.1:$EXPOSED_MQ_WEBSOCKET_PORT:15674"
    environment:
     - "RABBITMQ_USER=yNNp7VJS"
     - "RABBITMQ_PASS=1ElYfGNW"
  database:
    image: $DOCKER_REPOSITORY/deepsense-h2:$DOCKER_TAG
    ports:
     - "127.0.0.1:$EXPOSED_DB_PORT:1521"
    volumes:
      - "./h2-data:/opt/h2-data:rw"
  library:
    image: $DOCKER_REPOSITORY/deepsense-libraryservice:$DOCKER_TAG
    ports:
     - "127.0.0.1:$EXPOSED_LIBRARY_PORT:9083"
    volumes:
      - "library:/library"
volumes:
  library:
