# yaml added to end of docker-compose.yml if present in /etc/default/seahorse-dockercompose-network-settings
# Set to wanted subnet if default docker-compose subnet is not desired
networks:
  default:
    ipam:
      driver: default
      config:
      - subnet: 10.255.3.1/24
