# Copyright (c) 2015, CodiLime Inc.

---
- name: Deploy Workflow Manager package
  include: ../../../tasks/deploy_package.yml
  vars:
    artifactid: "{{wm_artifact_id}}"
    version: "{{wm_version}}"
    package_path: "{{download_dir}}/{{artifactid}}.zip"

- name: Create config file
  template: src=application.conf.j2 dest="{{install_dir}}/application.conf"

- name: Force supervisor restart
  command: /bin/true
  notify: restart supervisor
