# Copyright (c) 2015, CodiLime Inc.

---
- name: Assures ds-spark docker directory exists
  file: path="{{docker_dir}}/spark" state=directory

- name: Copy ds-spark docker files
  copy: src="./" dest="{{docker_dir}}/spark/"

- name: Create ds-spark dockerfile
  template: src=Dockerfile.j2 dest="{{docker_dir}}/spark/Dockerfile"

- name: Create ds-spark spark installation script
  template: src=scripts/install.sh dest="{{docker_dir}}/spark/scripts/install.sh"

# TODO: It is very hard to retrieve this file from Artifactory in standard way
- name: Download Spark package (compiled for DS) from Artifactory
  get_url: dest="{{docker_dir}}/spark/" url="http://10.10.1.77:8081/artifactory/simple/ext-third-party/spark/spark/{{spark_version}}/{{spark_package_filename}}"

- name: Set ds-spark scripts mode
  file: path="{{docker_dir}}/spark/scripts/{{item}}" mode=0755
  with_items:
    - install.sh
    - init.sh
    - run.sh

- name: Build ds-spark docker image
  docker_image: path="{{docker_dir}}/spark" name="{{ds_spark_docker_image}}" state=build
