- name: Assures docker dir exists
  file: path={{ds_haproxy_download_dir}} state=directory

- name: Create haproxy dockerfile
  template: src=Dockerfile.j2 dest="{{ds_haproxy_download_dir}}/Dockerfile"

- name: Create haproxy configuration file
  template: src=haproxy.cfg.j2 dest="{{ds_haproxy_download_dir}}/haproxy.cfg"

- name: Copy deepsense.io SSL certificate file
  copy: src=deepsense.io.pem dest="{{ds_haproxy_download_dir}}/deepsense.io.pem" owner=root group=root mode=0400

- name: Copy editor.seahorse.deepsense.io SSL certificate file
  copy: src=editor.seahorse.deepsense.io.pem dest="{{ds_haproxy_download_dir}}/editor.seahorse.deepsense.io.pem" owner=root group=root mode=0400

- name: Build haproxy docker image
  command: docker build -t {{ds_haproxy_docker_image}} {{ds_haproxy_download_dir}}
