# Copyright (c) 2016, CodiLime Inc.

---
dependencies:
- { role: supervisedprogram,
    program: {
      name: 'LivyServer',
      command: '{{install_dir}}/{{livy_artifactid}}/bin/livy-server',
      directory: "{{install_dir}}",
      environment: 'SPARK_HOME="{{spark_install_dir}}/spark",PYTHONPATH="{{spark_install_dir}}/spark/python:{{spark_install_dir}}/spark/python/build:$PYTHONPATH"',
      autostart: true,
      autorestart: true,
      startretries: 3,
      stdout_logfile: "{{install_dir}}/{{livy_artifactid}}/std.out",
      stdout_logfile_maxbytes: 0,
      stderr_logfile: "{{install_dir}}/{{livy_artifactid}}/std.err",
      stderr_logfile_maxbytes: 0,
      user: ubuntu,
    }
  }
