# Copyright (c) 2015, CodiLime Inc.

---
- name: Assures docker dir exists
  file: path={{docker_dir}}/frontend state=directory

- name: Create frontend dockerfile
  template: src=Dockerfile.j2 dest="{{docker_dir}}/frontend/Dockerfile"

- name: Create run.sh file
  template: src="run.sh" dest="{{docker_dir}}/frontend/run.sh"

- name: Copy config files
  copy: src="{{item}}" dest="{{docker_dir}}/frontend/{{item}}"
  with_items:
    - config.js
    - default.conf
    - htpasswd

- name: Build frontend docker image
  command: docker build -t {{ds_frontend_docker_image}} {{docker_dir}}/frontend/
