# Copyright (c) 2015, CodiLime Inc.

---

- include: ../../../tasks/get_frontend_artifact_path.yml

- name: Install nginx
  apt: package=nginx state=present

- name: Assure directory exists
  file: path="{{frontend_dir}}" state=directory

- name: Copy frontend config file
  copy: src="config.js" dest="{{frontend_dir}}/config.js"

- name: Copy installation script
  template: src="install.sh.j2" dest="{{frontend_dir}}/install.sh" mode=0755

- name: Install frontend
  shell: "{{frontend_dir}}/install.sh"

- name: Copy nginx config file
  copy: src="default.conf" dest="/etc/nginx/conf.d/default.conf"

- name: Restart nginx
  service: name=nginx state=restarted
