# Copyright (c) 2015, CodiLime Inc.

---

- name: Assure directory exists
  file: path="{{frontend_dir}}" state=directory

- name: Copy frontend package
  copy: src={{download_dir}}/{{frontend_artifact_id}}.zip dest={{frontend_dir}}

- name: Copy frontend config file
  copy: src="config.js" dest="{{frontend_dir}}/config.js"

- name: Copy installation script
  template: src="install.sh.j2" dest="{{frontend_dir}}/install.sh" mode=0755

- name: Install frontend
  shell: "{{frontend_dir}}/install.sh"

- name: Restart nginx
  service: name=nginx state=restarted
