# meta file for supervisor
---
galaxy_info:
  author: Mischa ter Smitten
  company: Oefenweb.nl B.V.
  description: Set up the latest or a specific version of supervisor in Ubuntu systems
  license: MIT
  min_ansible_version: 1.5
  platforms:
  - name: Ubuntu
    versions:
      - precise
      - trusty
  categories:
    - web
    - system
    - networking
    - monitoring
dependencies: []
