version: '2'
services:
  sparkMaster:
    image: deepsense/docker-spark-standalone:local
    ports:
      - "8080:8080"
      - "4040:4040"
      - "7077:7077"
    entrypoint: "/usr/bin/supervisord --configuration=/opt/conf/master.conf"
    links:
      - hdfs
  sparkSlave1:
    image: deepsense/docker-spark-standalone:local
    entrypoint: "/usr/bin/supervisord --configuration=/opt/conf/slave.conf"
    links:
      - sparkMaster
      - hdfs
  sparkSlave2:
    image: deepsense/docker-spark-standalone:local
    entrypoint: "/usr/bin/supervisord --configuration=/opt/conf/slave.conf"
    links:
      - sparkMaster
      - hdfs
  hdfs:
    image: sequenceiq/hadoop-docker:2.7.1
    hostname: "hdfs"
    entrypoint: "/etc/bootstrap.sh -d"