# tasks file for supervisor
---
- name: update group configuration files (present)
  template:
    src: etc/supervisor/conf.d/group.conf.j2
    dest: "/etc/supervisor/conf.d/{{ item.key }}.conf"
    owner: root
    group: root
    mode: 0640
  with_dict: supervisor_groups_present
  when: supervisor_groups_present
  notify: restart supervisor
  tags: [configuration, supervisor, supervisor-configuration-groups]

- name: update group configuration files (absent)
  file:
    path: "/etc/supervisor/conf.d/{{ item.key }}.conf"
    state: absent
  with_dict: supervisor_groups_absent
  when: supervisor_groups_absent
  notify: restart supervisor
  tags: [configuration, supervisor, supervisor-configuration-groups]
