# tasks file for supervisor
---
- include: install.yml
- include: configure.yml
- include: programs.yml
- include: groups.yml

- name: start and enable service
  service:
    name: supervisor
    state: started
    enabled: yes
  tags: [configuration, supervisor, supervisor-start-enable-service]
