# tasks file for supervisor
---
- name: update program configuration files (present)
  template:
    src: etc/supervisor/conf.d/program.conf.j2
    dest: "/etc/supervisor/conf.d/{{ item.key }}.conf"
    owner: root
    group: root
    mode: 0640
  with_dict: supervisor_programs_present
  when: supervisor_programs_present
  notify: restart supervisor
  tags: [configuration, supervisor, supervisor-configuration-programs]

- name: update program configuration files (absent)
  file:
    path: "/etc/supervisor/conf.d/{{ item.key }}.conf"
    state: absent
  with_dict: supervisor_programs_absent
  when: supervisor_programs_absent
  notify: restart supervisor
  tags: [configuration, supervisor, supervisor-configuration-programs]
