# Copyright (c) 2015, CodiLime Inc.

wm_artifact_id: deepsense-workflowmanager
wm_version: 0.2.0-SNAPSHOT
wm_build_version: latest

frontend_artifact_id: deepsense-frontend
frontend_version: latest

workflowexecutor_artifact_id: deepsense-workflowexecutor
workflowexecutor_version: latest
workflowexecutor_build_version: 1.0.0-SNAPSHOT
