# Copyright (c) 2015, CodiLime Inc.

artifactory_host: 10.10.1.77
artifactory_port: 8081
artifactory_repository: deepsense-backend-snapshot
artifactory_base_url: http://{{artifactory_host}}:{{artifactory_port}}/artifactory
