# Copyright (c) 2015, CodiLime Inc.

- name: Create vagrant directory
  file: path=vagrant state=directory

- name: Create Vagrantfile
  template: src=Vagrantfile.j2 dest=vagrant/Vagrantfile

- name: Copy image_cleanup.sh.j2 template file
  copy: src=image_cleanup.sh.j2 dest=vagrant/image_cleanup.sh.j2

- name: Remove old box file
  file: path=vagrant/deepsense-vm.box state=absent
