# Copyright (c) 2015, CodiLime Inc.

---
- include: ../../../tasks/deploy_package.yml
  vars:
    artifactid: "{{dms_artifact_id}}"
    version: "{{dms_version}}"
    package_path: "{{download_dir}}/{{artifactid}}.zip"

- { include: ../../supervisedprogram/tasks/main.yaml,
    program: {
      name: 'DeployModelService',
      command: '{{install_dir}}/deepsense-deploy-model-service/bin/deepsense-deploy-model-service -DlogFile=/home/ubuntu/log/deepsense/dms/deepsense-deploy-model-service',
      directory: "{{install_dir}}",
      autostart: true,
      autorestart: true,
      startretries: 3,
      stdout_logfile: "{{install_dir}}/std.out",
      stdout_logfile_maxbytes: 0,
      stderr_logfile: "{{install_dir}}/std.err",
      stderr_logfile_maxbytes: 0,
      user: ubuntu,
    }
  }

- name: Force supervisor restart
  command: /bin/true
  notify: restart supervisor
