# Copyright (c) 2015, CodiLime Inc.

---
wm_server_port: 9080

wm_auth_service_identity: "service:workflow-manager"
wm_auth_service_password: "fahda0joek3aeBah"
auth_service_timeout_connection: 1000

roles_workflows_get: "workflows:get"
roles_workflows_update: "workflows:update"
roles_workflows_create: "workflows:create"
roles_workflows_list: "workflows:list"
roles_workflows_delete: "workflows:delete"
roles_workflows_launch: "workflows:launch"
roles_workflows_abort: "workflows:abort"

workflows_api_prefix: "v1/workflows"
operations_api_prefix: "v1/operations"
models_api_prefix: "v1/models"

workflows_timeout: 3000

cassandra_host: "{{master_host}}"
cassandra_reconnect_delay: 5000
cassandra_user: cassandra
cassandra_pass: cassandra
wm_cassandra_table: workflows
wm_cassandra_keyspace: workflowmanager
