# Copyright (c) 2015, CodiLime Inc.

- name: Create directory for java installation
  file: path="{{java_install_directory}}" state=directory

- name: Copy java package to remote machine
  copy: src="{{download_dir}}/{{java_package_name}}" dest="{{java_upload_path}}"

- name: Extract java package
  shell: "tar -zxf {{java_upload_path}} -C {{java_install_directory}}"

- name: Update-alternatives for java
  shell: "update-alternatives --install /usr/bin/java java {{java_bin_directory}}/java 2000"

- name: Set alternative for java
  shell: "update-alternatives --set java {{java_bin_directory}}/java"

- name: Update-alternatives for javac
  shell: "update-alternatives --install /usr/bin/javac javac {{java_bin_directory}}/javac 2000"

- name: Set alternative for javac
  shell: "update-alternatives --set javac {{java_bin_directory}}/javac"
