# Copyright (c) 2015, CodiLime Inc.

---
- name: Create install directory
  file: path="{{install_dir}}" state=directory mode=0755 owner=ubuntu

- name: Copy WorkflowExecutor jar file
  copy: src={{download_dir}}/{{workflowexecutor_artifact_id}}.jar dest={{install_dir}}

- name: Create extra-jars directory
  file: path="{{extra_jars}}" state=directory mode=0755 owner=ubuntu

- name: Copy MySql JDBC connector
  copy: src={{download_dir}}/{{mysql_connector_jar_id}}.jar dest={{extra_jars}}

- name: Copy Postgres JDBC connector
  copy: src={{download_dir}}/{{postgresql_connector_jar_id}}.jar dest={{extra_jars}}

- name: Force supervisor restart
  command: /bin/true
  notify: restart supervisor
