# Copyright (c) 2015, CodiLime Inc.

---
- name: Create install directory
  file: path="{{install_dir}}" state=directory mode=0755 owner=ubuntu

- name: Copy WorkflowExecutor jar file
  copy: src={{download_dir}}/{{workflowexecutor_artifact_id}}.jar dest={{install_dir}}

- name: Create extra-jars directory
  file: path="{{extra_jars}}" state=directory mode=0755 owner=ubuntu

- name: Copy MySql JDBC connector
  copy: src={{download_dir}}/{{mysql_connector_jar_id}}.jar dest={{extra_jars}}

- name: Copy Postgres JDBC connector
  copy: src={{download_dir}}/{{postgresql_connector_jar_id}}.jar dest={{extra_jars}}

- { include: ../../supervisedprogram/tasks/main.yaml,
    program: {
      name: 'WorkflowExecutor',
      environment: 'SPARK_HOME="{{spark_install_dir}}/spark", PYTHONPATH="{{spark_install_dir}}/spark/python:{{spark_install_dir}}/spark/python/build:$PYTHONPATH"',
      command: '{{spark_install_dir}}/spark/bin/spark-submit --class io.deepsense.workflowexecutor.WorkflowExecutorApp --master local[8] --driver-class-path "{{extra_jars}}/{{mysql_connector_jar_id}}.jar:{{extra_jars}}/{{postgresql_connector_jar_id}}.jar:{{workflowexecutor_artifact_id}}.jar" {{workflowexecutor_artifact_id}}.jar --interactive-mode -m localhost -p {{workflowexecutor_artifact_id}}.jar',
      directory: "{{install_dir}}",
      autostart: true,
      autorestart: true,
      startretries: 3,
      stdout_logfile: "{{install_dir}}/std.out",
      stdout_logfile_maxbytes: 0,
      stderr_logfile: "{{install_dir}}/std.err",
      stderr_logfile_maxbytes: 0,
      user: ubuntu,
    }
  }

- name: Force supervisor restart
  command: /bin/true
  notify: restart supervisor
