# Copyright (c) 2015, CodiLime Inc.

---
- name: Assures docker dir exists
  file: path={{hadoop_docker_dir}} state=directory

- name: Copy dockerfile
  copy: src="Dockerfile" dest="{{hadoop_docker_dir}}/Dockerfile"

- name: Copy scripts
  copy: src="scripts/" dest="{{hadoop_docker_dir}}/scripts/"

- name: Copy configuration
  copy: src="conf/" dest="{{hadoop_docker_dir}}/conf/"

- name: Set scripts mode
  file: path="{{hadoop_docker_dir}}/scripts/{{item}}" mode=0755
  with_items:
    - install.sh
    - init.sh
    - run.sh

- name: Build Hadoop docker image
  docker_image: path="{{hadoop_docker_dir}}" name="ds-hadoop" state=build
