# Copyright (c) 2015, CodiLime Inc.

---
- name: Perform cassandra migration
  hosts: cassandra
  user: ubuntu
  sudo: yes
  vars_files:
    - vars/env.yml
    - vars/deployment.yml
  roles:
    - { role: cassandra_migration,
        cql_dir: "{{wm_cql_dir}}",
        module: "workflowmanager"
      }
