# Copyright (c) 2015, CodiLime Inc.

- name: Collects DeepSense.io installables
  hosts: localhost
  vars_files:
    - vars/deployment.yml
    - vars/artifacts.yml
  tasks:
    - include: tasks/create_download_dir.yml
    - include: tasks/export_docker_container.yml docker_image=cassandra

- name: Copies Cassandra image
  hosts: cassandra
  user: ubuntu
  sudo: yes
  vars_files:
    - vars/deployment.yml
    - vars/artifacts.yml
  tasks:
    - include: tasks/copy_docker_image.yml docker_tar_image=cassandra-docker.tgz docker_dir=/tmp/docker-ansible

- name: Imports Cassandra image
  hosts: cassandra
  user: ubuntu
  sudo: yes
  vars_files:
    - vars/deployment.yml
    - vars/artifacts.yml

  tasks:
    - include: tasks/import_docker_container.yml docker_image=cassandra docker_dir=/tmp/docker-ansible

- name: Ensure Cassandra data directory is present
  hosts: cassandra
  user: ubuntu
  sudo: yes
  vars_files:
    - vars/docker.yml
  tasks:
    - name: Create Cassandra directory
      file: path="{{cassandra_data_dir}}" state=directory owner=ubuntu group=ubuntu mode=755

- name: Runs Cassandra image
  hosts: cassandra
  user: ubuntu
  sudo: yes
  vars_files:
    - vars/docker.yml
  roles:
    - { role: cassandra,
        cassandra_server_port: 11011,
        data_dir: "{{cassandra_data_dir}}"
      }
