# Copyright (c) 2015, CodiLime Inc.

########
# Removes all docker containers and images.
########

---
- name: Docker cleanup
  hosts: cleanup
  user: ubuntu
  sudo: yes
  tasks:
    - name: Remove all docker containers
      shell: if [ -n "$(docker ps -a -q)" ] ; then docker rm -f $(docker ps -a -q); fi

    - name: Remove all docker images
      shell: if [ -n "$(docker images -q)" ] ; then docker rmi -f $(docker images -q) || exit 0; fi
