# Copyright (c) 2015, CodiLime Inc.

---
- name: "Downloads java packages from repository"
  hosts: localhost
  vars_files:
    - vars/deployment.yml
    - vars/java.yml
  tasks:
    - include: tasks/create_download_dir.yml
    - name: "Download java package"
      artifactory:
        base_url: "{{artifactory_base_url}}"
        repository: "ext-third-party"
        groupid: "java"
        artifactid: "java"
        version: "{{java_artifact_version}}"
        path: "{{download_dir}}/"
        filename: "{{java_package_name}}"


- name: "Install java on target machines"
  hosts: java_hosts
  user: ubuntu
  sudo: yes
  vars_files:
    - vars/deployment.yml
    - vars/java.yml
  roles:
    - java
