# Copyright (c) 2015, CodiLime Inc.

---
- name: Builds rabbitmq docker images
  hosts: localhost
  vars_files:
    - vars/env.yml
    - vars/rabbitmq.yml
  vars:
    docker_dir: "/tmp/docker-ansible"
  roles:
    - rabbitmq

- name: Exports rabbitmq docker image
  hosts: localhost
  vars_files:
    - vars/env.yml
    - vars/rabbitmq.yml
  tasks:
    - include: tasks/save_docker_image.yml docker_image={{rabbitmq_docker_image}} download_dir="{{rabbitmq_download_dir}}"

- name: Copies rabbitmq docker image
  hosts: frontend
  user: ubuntu
  sudo: yes
  vars_files:
    - vars/env.yml
    - vars/rabbitmq.yml
  tasks:
    - name: Assures docker dir exists
      file: path={{rabbitmq_download_dir}} state=directory
    - include: tasks/copy_docker_image.yml docker_tar_image={{rabbitmq_docker_image}}-docker.tar docker_dir={{rabbitmq_download_dir}} download_dir="{{rabbitmq_download_dir}}"

- name: Imports rabbitmq docker image
  hosts: frontend
  user: ubuntu
  sudo: yes
  vars_files:
    - vars/env.yml
    - vars/rabbitmq.yml
  tasks:
    - include: tasks/load_docker_image.yml docker_image={{rabbitmq_docker_image}} docker_dir={{rabbitmq_download_dir}}

- name: Runs rabbitmq image
  hosts: frontend
  user: ubuntu
  sudo: yes
  vars_files:
    - vars/env.yml
    - vars/rabbitmq.yml
  tasks:
    - name: Register running Docker containers
      register: docker_containers
      command: docker ps -a

    - name: Remove previous container
      command: docker rm -f {{rabbitmq_docker_image}}
      when: docker_containers.stdout.find("{{rabbitmq_docker_image}}") != -1

    - name: Run rabbitmq container
      docker:
        name: "{{rabbitmq_docker_image}}"
        image: "{{rabbitmq_docker_image}}"
        state: started
        restart_policy: always
        ports:
          - "{{rabbitmq_server_ip}}:5671:5671"
          - "{{rabbitmq_server_ip}}:5672:5672"
          - "{{rabbitmq_server_ip}}:15674:15674"
          - "{{rabbitmq_server_ip}}:15672:15672"
          - "{{rabbitmq_server_ip}}:61613:61613"
