# Copyright (c) 2016, CodiLime Inc.

---
- name: Download SessionManager package
  hosts: localhost
  vars_files:
    - vars/deployment.yml
    - vars/artifacts.yml
    - vars/supervisor.yml
  tasks:
    - include: tasks/create_download_dir.yml
    - include: tasks/artifactory_get.yml artifact_path={{sm_artifact_path}} artifactid={{sm_artifact_id}}
    - include: tasks/download_supervisor.yml

- name: Set up SessionManager application
  hosts: master
  user: ubuntu
  sudo: yes
  vars_files:
    - vars/deployment.yml
    - vars/artifacts.yml
    - vars/docker.yml
    - vars/supervisor.yml
  roles:
    - supervisor
    - { role: sessionmanager,
        install_dir: "{{sm_install_dir}}",
        sessionmanager_workflowexecutor_jar: "{{wm_jar_path}}"
      }
