# Copyright (c) 2015, CodiLime Inc.

---
- name: Downloads Supervisor packages from Artifactory
  hosts: localhost
  vars_files:
    - vars/deployment.yml
    - vars/supervisor.yml
  roles:
    - supervisor-dependencies-downloader


- name: Install and configure Supervisor
  hosts: vagrant
  user: ubuntu
  sudo: yes
  vars_files:
    - vars/deployment.yml
    - vars/supervisor.yml
  roles:
    - supervisor
