# Copyright (c) 2015, CodiLime Inc.

- hosts: seahorse-vm
  gather_facts: false
  tasks:
    - include: tasks/install_docker.yml
    - include: tasks/install_openjdk.yml
    - shell: usermod -a -G vagrant ubuntu

- include: cassandra.yml

- hosts: seahorse-vm
  gather_facts: false
  vars_files:
    - vars/env.yml
  tasks:
    - name: Wait for Cassandra to come up
      wait_for: host={{cassandra_server_ip}} port={{cassandra_server_port}}
    - name: Wait 15s for clients to reconnect
      wait_for: timeout=15

- hosts: localhost
  gather_facts: false
  vars_files:
    - vars/deployment.yml
  tasks:
    - include: tasks/get_frontend_artifact_path.yml
    - include: tasks/get_wm_artifact_path.yml
    - include: tasks/get_workflowexecutor_artifact_path.yml

- include: cassandra_migration.yml
- include: workflowmanager.yaml
- include: frontend.yml
- include: rabbitmq.yml
- include: install_spark.yml
- include: workflowexecutor.yaml
- include: notebook.yml

- hosts: seahorse-vm
  gather_facts: false
  vars_files:
    - vars/deployment.yml
    - vars/notebook.yml
  tasks:
    - template: src=vagrant/image_cleanup.sh.j2 dest=/root/image_cleanup.sh mode=755
    - shell: /root/image_cleanup.sh
    - file: path=/root/image_cleanup.sh state=absent
