# Copyright (c) 2015, CodiLime Inc.

- hosts: seahorse-vm
  gather_facts: false
  tasks:
    - apt: update_cache=yes
    - include: tasks/install_python_libs.yml
    - include: tasks/install_openjdk.yml
    - shell: usermod -a -G vagrant ubuntu

- hosts: localhost
  gather_facts: false
  vars_files:
    - vars/deployment.yml
  tasks:
    - include: tasks/get_frontend_artifact_path.yml
    - include: tasks/get_wm_artifact_path.yml
    - include: tasks/get_workflowexecutor_artifact_path.yml

- include: generate_examples.yml
- include: h2_migration.yml
- include: remove_examples.yml

- include: workflowmanager.yaml
- include: frontend.yml
- include: rabbitmq.yml
- include: install_spark.yml
- include: workflowexecutor.yaml
- include: notebook.yml
- include: livy.yml

- hosts: seahorse-vm
  gather_facts: false
  vars_files:
    - vars/deployment.yml
    - vars/notebook.yml
  tasks:
    - template: src=vagrant/image_cleanup.sh.j2 dest=/root/image_cleanup.sh mode=755
    - shell: /root/image_cleanup.sh
    - file: path=/root/image_cleanup.sh state=absent
