# Copyright (c) 2015, CodiLime Inc.

---
- name: Download WorkflowManager package
  hosts: localhost
  vars_files:
    - vars/deployment.yml
    - vars/artifacts.yml
    - vars/supervisor.yml
  tasks:
    - include: tasks/create_download_dir.yml
    - include: tasks/artifactory_get.yml artifact_path={{wm_artifact_path}} artifactid={{wm_artifact_id}}
    - include: tasks/download_supervisor.yml

- name: Set up WorkflowManager application
  hosts: master
  user: ubuntu
  sudo: yes
  vars_files:
    - vars/deployment.yml
    - vars/artifacts.yml
    - vars/supervisor.yml
    - vars/wm.yml
  roles:
    - supervisor
    - { role: workflowmanager,
        install_dir: "{{wm_install_dir}}"
      }
