# Copyright (c) 2015, CodiLime Inc.

---
- name: Download WorkflowExecutor packages
  hosts: localhost
  vars_files:
    - vars/env.yml
    - vars/deployment.yml
    - vars/artifacts.yml
    - vars/supervisor.yml
  tasks:
    - include: tasks/create_download_dir.yml
    - include: tasks/artifactory_get.yml artifact_path={{workflowexecutor_artifact_path}} artifactid={{workflowexecutor_artifact_id}} artifacttype=jar
    - include: tasks/download_supervisor.yml
    - include: tasks/artifactory_get.yml artifact_path={{mysql_connector_jar_path}} artifactid={{mysql_connector_jar_id}} artifacttype=jar
    - include: tasks/artifactory_get.yml artifact_path={{postgresql_connector_jar_path}} artifactid={{postgresql_connector_jar_id}} artifacttype=jar

- name: Set up WorkflowExecutor application
  hosts: master
  user: ubuntu
  sudo: yes
  vars_files:
    - vars/deployment.yml
    - vars/artifacts.yml
    - vars/env.yml
    - vars/main.yml
    - vars/docker.yml
    - vars/supervisor.yml
    - vars/install_spark.yml
  roles:
    - supervisor
    - { role: workflowexecutor,
        install_dir: "{{workflowexecutor_install_dir}}",
      }
